### PR TITLE
Add linux for travis. Change master to release branch to publish the binary

### PR DESCRIPTION
**Pull request by tbrand**
As title.

### CODE REVIEW

**Comment by tbrand** [comment]
From this PR, the release flow has been changed.
When merge `master` into `release`, the binary will be published.

**Comment by waghanza** [comment]
@tbrand Do'nt you prefer the `release` base on `tag` (btw, github releasing is base on **tag**)

**Comment by tbrand** [comment]
Tag is fixed in the release.rb script.

**Comment by waghanza** [comment]
@tbrand I see,  `travis`  run on each modification of `release` branch then tag / release

I thought about manual tagging, and `travis` run only on tag detections ;-)

**Comment by tbrand** [comment]
Yeah that makes sense. Could I do it on another PR?

**Comment by waghanza** [comment]
sure. It will keep a `cleaner` git history. If you need any help :heart:

**Comment by notramo** [comment]
@tbrand any progress on this?

**Comment by tbrand** [comment]
will do it later

**Comment by tbrand** [comment]
Fixed.

**Comment by tbrand** [comment]
I this I should close this now.

**Pull request closed without merging**
